### ISSUE TITLE
[BUG] Insecure parameter missing in restore Request?

### ISSUE THREAD

**Issue by an-tex** [instaclustr/instaclustr-icarus-go-client#3]
**Describe the bug**
The [backup operation request](https://github.com/instaclustr/instaclustr-icarus-go-client/blob/master/pkg/instaclustr_icarus/model_backup_operation_request.go#L41) contains the field `Insecure`. This field is missing in the [restore operation request](https://github.com/instaclustr/instaclustr-icarus-go-client/blob/master/pkg/instaclustr_icarus/model_restore_operation_request.go). I imagine it's needed there as well?

**Versions (please complete the following information):**
 - 1.0.5 (current)

**Comment by smiklosovic** [comment]
hi @an-tex 

good catch, yes, it is missing, feel free to prepare PR if you feel like it and I ll merge gladly.

Regards

**Comment by an-tex** [comment]
will do!
